server:
  port: 10010
spring:
  application:
    name: zuul-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api #路由前缀
  routes:
    item-service: /item/**